# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BarangayArchives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('scanned_pdf', models.FileField(blank=True, null=True, upload_to='barangay_scans/%Y/')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_doc', to='documents.barangaydocument')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
