# Generated by Django 6.0.2 on 2026-03-18 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='original_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document'),
        ),
    ]
