# Generated by Django 6.0.3 on 2026-04-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_barangayarchives_reference_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangayArchives',
        ),
    ]
