# Generated by Django 6.0.3 on 2026-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=20, null=True)),
                ('council_number', models.CharField(max_length=10, null=True)),
                ('session_time', models.CharField(max_length=10, null=True)),
                ('previous_session_date', models.DateField()),
                ('invocation_by', models.CharField(max_length=50, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('order_of_business', models.FileField(blank=True, null=True, upload_to='session/%Y/')),
                ('participants', models.TextField()),
                ('minutes', models.FileField(blank=True, null=True, upload_to='session/minutes/%Y/')),
            ],
        ),
    ]
