# Generated by Django 6.0.3 on 2026-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='agenda_finalized_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
