# Generated by Django 6.0.3 on 2026-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0002_session_agenda_finalized_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='agenda_finalized_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='previous_session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
