# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Hearing'), ('APPROVED', 'Approved on Committee Level'), ('FAILED', 'Did not pass Committee Level'), ('RESET', 'Reset for another hearing')], default='PENDING', max_length=20)),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='final_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_report', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='HearingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('attendance_notes', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('PENDING', 'No decision yet'), ('APPROVED', 'Approved on committee level'), ('RESET', 'Reset — another hearing needed'), ('FAILED', 'Did not pass committee level')], default='PENDING', max_length=20)),
                ('version_discussed', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='committee_level.committeereport')),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
    ]
