# Generated by Django 6.0.3 on 2026-04-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeereport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Hearing'), ('APPROVED', 'Approved on Committee Level'), ('FAILED', 'Did not pass Committee Level')], default='PENDING', max_length=20),
        ),
    ]
