# Generated by Django 6.0.3 on 2026-09-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee_level', '0002_alter_committeereport_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hearinglog',
            options={'ordering': ['-hearing_date', '-id']},
        ),
    ]
