# Generated by Django 6.0.3 on 2026-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_level', '0003_alter_hearinglog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeereport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Hearing Scheduled'), ('APPROVED', 'Approved on Committee Level'), ('FAILED', 'Did not pass Committee Level')], default='PENDING', max_length=20),
        ),
    ]
