# Generated by Django 6.0.3 on 2026-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_level', '0004_alter_committeereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearinglog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
