# Generated by Django 6.0.2 on 2026-03-18 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('doc_type', models.CharField(choices=[('ORDINANCE', 'Ordinance'), ('RESOLUTION', 'Resolution')], default='ORDINANCE', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FILED', 'Filed'), ('FIRST_READING', 'First Reading'), ('COMMITTEE', 'Committee Hearing'), ('SECOND_READING', 'Second Reading'), ('THIRD_READING', 'Third Reading'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('current_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_docs', to=settings.AUTH_USER_MODEL)),
                ('referred_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committees.committee')),
            ],
        ),
    ]
