# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangay', '0001_initial'),
        ('committees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_type', models.CharField(choices=[('ORDINANCE', 'Ordinance'), ('RESOLUTION', 'Resolution')], default='ORDINANCE', max_length=15)),
                ('status', models.CharField(choices=[('GHOST', 'Ghost Draft'), ('DRAFT', 'Draft'), ('FILED', 'Filed'), ('FIRST_READING', 'First Reading'), ('REFERRED', 'Reffered to Committee'), ('COMMITTEE', 'Committee Hearing'), ('SECOND_READING', 'Second Reading'), ('THIRD_READING', 'Third Reading'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('current_version', models.IntegerField(default=1)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, max_length=600, null=True)),
                ('scanned_pdf', models.FileField(blank=True, null=True, upload_to='barangay_scans/%Y/')),
                ('origin_barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangay.barangay')),
                ('referred_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committees.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('doc_type', models.CharField(choices=[('ORDINANCE', 'Ordinance'), ('RESOLUTION', 'Resolution')], default='ORDINANCE', max_length=15)),
                ('status', models.CharField(choices=[('GHOST', 'Ghost Draft'), ('DRAFT', 'Draft'), ('FILED', 'Filed'), ('FIRST_READING', 'First Reading'), ('REFERRED', 'Reffered to Committee'), ('COMMITTEE', 'Committee Hearing'), ('SECOND_READING', 'Second Reading'), ('THIRD_READING', 'Third Reading'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('current_version', models.IntegerField(default=1)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_docs', to=settings.AUTH_USER_MODEL)),
                ('referred_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee', to='committees.committee')),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_notes', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
