# Generated by Django 6.0.3 on 2026-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='amended_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='amendment_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('FINALIZED', 'Amendments Finalized'), ('NO_AMENDMENTS', 'No Amendments Made')], default='IN_PROGRESS', max_length=20, null=True),
        ),
    ]
