# Generated by Django 6.0.3 on 2026-04-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_amended_content_document_amendment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangaydocument',
            name='status',
            field=models.CharField(choices=[('GHOST', 'Ghost Draft'), ('DRAFT', 'Draft'), ('FILED', 'Filed'), ('FIRST_READING', 'First Reading'), ('REFERRED', 'Reffered to Committee'), ('OTHER_MATTERS', 'Other Matters'), ('COMMITTEE', 'Committee Hearing'), ('SECOND_READING', 'Second Reading'), ('THIRD_READING', 'Third Reading'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='barangaydocument',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(),
        ),
    ]
