# Generated by Django 6.0.3 on 2026-04-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_barangayfiles'),
        ('documents', '0003_alter_barangaydocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_barangay_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_drafts', to='barangay.barangayfiles'),
        ),
        migrations.AlterField(
            model_name='barangaydocument',
            name='origin_barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barangay', to='barangay.barangay'),
        ),
        migrations.AlterField(
            model_name='barangaydocument',
            name='status',
            field=models.CharField(choices=[('GHOST', 'Ghost Draft'), ('DRAFT', 'Draft'), ('FILED', 'Filed'), ('FIRST_READING', 'First Reading'), ('REFERRED', 'Reffered to Committee'), ('OTHER_MATTERS', 'Other Matters'), ('COMMITTEE', 'Committee Hearing'), ('UNFINISHED_BUSINESS', 'Unfinished Business'), ('SECOND_READING', 'Second Reading'), ('THIRD_READING', 'Third Reading'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default='DRAFT', max_length=20),
        ),
    ]
