# Generated by Django 6.0.3 on 2026-04-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_delete_barangayarchives'),
        ('documents', '0004_document_source_barangay_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session_included',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BarangayDocument',
        ),
    ]
