# Generated by Django 6.0.3 on 2026-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_session_included_delete_barangaydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_participation',
            field=models.BooleanField(default=False),
        ),
    ]
