# Generated by Django 6.0.3 on 2026-05-06 23:27

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_public_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('doc_type', models.CharField(choices=[('ORDINANCE', 'Ordinance'), ('RESOLUTION', 'Resolution')], max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='legacy_documents/%Y/')),
                ('extracted_text', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'reference_no'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
