# Generated by Django 6.0.3 on 2026-05-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_legacydocument_document_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacydocument',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to='legacy_documents/%Y/'),
        ),
        migrations.AlterField(
            model_name='legacydocument',
            name='title',
            field=models.CharField(max_length=700),
        ),
    ]
