# Generated by Django 6.0.3 on 2026-05-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_legacydocument_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacydocument',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
