import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentchunk'),
    ]

    operations = [
        # Step 1: clear embeddings before altering column dimensions.
        # document_chunk rows are deleted (NOT NULL constraint) — they will be
        # re-generated by running embed_documents after the migration.
        # document and legacy_document embeddings are nullified (nullable cols).
        migrations.RunSQL(
            sql="""
                DELETE FROM document_chunk;
                UPDATE documents_document       SET embedding = NULL;
                UPDATE documents_legacydocument SET embedding = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: change all three columns to 768 dimensions (nomic-embed-text)
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='legacydocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
