# Generated by Django 6.0.3 on 2026-05-30 03:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_vector_768_nomic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('law_number', models.CharField(help_text='e.g. Republic Act No. 7160', max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what the law covers')),
                ('content', models.TextField(help_text='Full text of the law — paste or type here')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['law_number'],
            },
        ),
        migrations.CreateModel(
            name='NationalLawChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_type', models.CharField(default='SECTION', max_length=50)),
                ('chunk_index', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.nationallaw')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
