# Generated by Django 6.0.3 on 2026-05-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_national_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationallaw',
            name='ocr_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nationallaw',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF — text will be extracted automatically', null=True, upload_to='national_laws/'),
        ),
        migrations.AlterField(
            model_name='nationallaw',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted or manually entered full text'),
        ),
    ]
