# Generated by Django 6.0.3 on 2026-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilors', '0001_initial'),
        ('documents', '0017_sanitize_existing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='participating_councilors',
            field=models.ManyToManyField(blank=True, related_name='participated_documents', to='councilors.councilor'),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/%Y/'),
        ),
    ]
