# Generated by Django 6.0.3 on 2026-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_participating_councilors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='flagged_similarity_hashes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
