# Generated by Django 6.0.3 on 2026-08-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_flagged_similarity_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='margin_bottom_cm',
            field=models.FloatField(default=2.54),
        ),
        migrations.AddField(
            model_name='document',
            name='margin_left_cm',
            field=models.FloatField(default=2.54),
        ),
        migrations.AddField(
            model_name='document',
            name='margin_right_cm',
            field=models.FloatField(default=2.54),
        ),
        migrations.AddField(
            model_name='document',
            name='margin_top_cm',
            field=models.FloatField(default=2.54),
        ),
        migrations.AddField(
            model_name='document',
            name='page_orientation',
            field=models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='page_size',
            field=models.CharField(choices=[('A4', 'A4'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A4', max_length=10),
        ),
    ]
