# Generated by Django 6.0.3 on 2026-08-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_margin_bottom_cm_document_margin_left_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WopiLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_value', models.CharField(max_length=1024)),
                ('locked_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wopi_lock', to='documents.document')),
            ],
        ),
    ]
