# Generated by Django 6.0.3 on 2026-08-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_wopilock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WopiLock',
        ),
    ]
