# Generated by Django 6.0.3 on 2026-09-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_delete_wopilock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('ORDINANCE', 'Ordinance'), ('RESOLUTION', 'Resolution')], default='', max_length=15),
        ),
    ]
