# Generated by Django 6.0.3 on 2026-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_document_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ORDINANCE', 'Ordinance'), ('RESOLUTION', 'Resolution')], max_length=15)),
                ('year', models.IntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'year'), name='unique_doc_type_year_counter')],
            },
        ),
    ]
