# Generated by Django 6.0.3 on 2026-09-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_documentreferencecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacydocument',
            name='reference_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
