# Generated by Django 6.0.3 on 2026-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Modified'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('FILE', 'Filed'), ('MOVE', 'Status Change'), ('RETURN', 'Returned'), ('PASSWORD_CHANGE', 'Password Changed')], max_length=20),
        ),
    ]
