# Generated by Django 6.0.3 on 2026-04-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_pdf', models.FileField(blank=True, null=True, upload_to='barangay_scans/%Y/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, max_length=600, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
                ('origin_barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangay.barangay')),
            ],
        ),
    ]
