# Generated by Django 6.0.3 on 2026-04-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_barangayfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangayfiles',
            old_name='reference_no',
            new_name='title',
        ),
    ]
