# Generated by Django 6.0.3 on 2026-04-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0003_rename_reference_no_barangayfiles_title'),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayfiles',
            name='referred_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committees.committee'),
        ),
    ]
