# Generated by Django 6.0.3 on 2026-09-04 06:48
# Hand-edited: makemigrations defaulted to remove+add (no interactive
# prompt in a non-interactive shell to confirm a rename) — RenameField is
# the more correct representation of what actually happened (barangay
# uploads switched from PDF to docx, same field repurposed) and preserves
# any existing files instead of dropping the column.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0004_barangayfiles_referred_committee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangayfiles',
            old_name='scanned_pdf',
            new_name='uploaded_docx',
        ),
        migrations.AlterField(
            model_name='barangayfiles',
            name='uploaded_docx',
            field=models.FileField(blank=True, null=True, upload_to='barangay_uploads/%Y/'),
        ),
    ]
