# Generated by Django 6.0.3 on 2026-04-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('republic_name', models.CharField(default='Republic of the Philippines', max_length=255)),
                ('city_name', models.CharField(default='City of San Juan, Metro Manila', max_length=255)),
                ('office_name', models.CharField(default='Office of the Sangguniang Panlungsod', max_length=255)),
                ('system_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('current_council_number', models.IntegerField(default=8)),
                ('default_venue', models.TextField(default='Session Hall, Room 214 of City of San Juan Government Center')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Setting',
            },
        ),
    ]
