# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Councilor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('district', models.IntegerField(choices=[(1, 'District 1'), (2, 'District 2')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='councilors/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if they are no longer in office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='councilor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
